### ISSUE TITLE
Unable to install Awas in OSATE 2.9.0

### ISSUE THREAD

**Issue by stevevestal** [sireum/v3-awas#1]
When I try to install, I get the error

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.ui,3.18.0.v20151116-1930

**Comment by stevevestal** [comment]
This can be fixed by having users first install "Mylyn Context Connector: Eclipse IDE" from the main Eclipse Repository URL that appears in the Work with... list.

**Comment by thari** [comment]
I am unable to reproduce it, but I have faced this error before. Cleaning my global P2 Pool usually resolves it.
